"""add Phase 3 run tracking models

Revision ID: 2bb8dea251ae
Revises: 29dea12b3605
Create Date: 2026-02-26 09:00:41.755131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb8dea251ae'
down_revision: Union[str, Sequence[str], None] = '29dea12b3605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('distance_miles', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('avg_pace_seconds', sa.Integer(), nullable=True),
    sa.Column('elevation_gain_ft', sa.Float(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('gps_polyline', sa.Text(), nullable=True),
    sa.Column('run_type', sa.String(length=20), nullable=True),
    sa.Column('weather', sa.String(length=100), nullable=True),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('whoop_recovery_score', sa.Float(), nullable=True),
    sa.Column('whoop_strain', sa.Float(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('running_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=30), nullable=True),
    sa.Column('target_weekly_miles', sa.Float(), nullable=True),
    sa.Column('current_weekly_miles', sa.Float(), nullable=True),
    sa.Column('current_plan', sa.Text(), nullable=True),
    sa.Column('plan_week', sa.Integer(), nullable=False),
    sa.Column('is_deload_week', sa.Boolean(), nullable=False),
    sa.Column('estimated_easy_pace', sa.Integer(), nullable=True),
    sa.Column('estimated_tempo_pace', sa.Integer(), nullable=True),
    sa.Column('estimated_interval_pace', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('distance_label', sa.String(length=30), nullable=False),
    sa.Column('time_seconds', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('mile_number', sa.Integer(), nullable=False),
    sa.Column('pace_seconds', sa.Integer(), nullable=False),
    sa.Column('elevation_change_ft', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_splits')
    op.drop_table('personal_records')
    op.drop_table('running_profiles')
    op.drop_table('run_sessions')
    # ### end Alembic commands ###
