"""add_saved_routes_and_route_id

Revision ID: 66b0f5ef4c06
Revises: 97c8cc3aa083
Create Date: 2026-02-26 14:20:22.609649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b0f5ef4c06'
down_revision: Union[str, Sequence[str], None] = '97c8cc3aa083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('waypoints', sa.Text(), nullable=True),
    sa.Column('polyline', sa.Text(), nullable=True),
    sa.Column('distance_miles', sa.Float(), nullable=False),
    sa.Column('elevation_gain_ft', sa.Float(), nullable=True),
    sa.Column('route_type', sa.String(length=30), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('times_run', sa.Integer(), nullable=False),
    sa.Column('best_time_seconds', sa.Integer(), nullable=True),
    sa.Column('last_run_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('run_sessions', sa.Column('route_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_sessions', 'route_id')
    op.drop_table('saved_routes')
    # ### end Alembic commands ###
