"""phase4 training plans and run updates

Revision ID: 97c8cc3aa083
Revises: 2bb8dea251ae
Create Date: 2026-02-26 11:36:30.940591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c8cc3aa083'
down_revision: Union[str, Sequence[str], None] = '2bb8dea251ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=30), nullable=False),
    sa.Column('fitness_level', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('total_weeks', sa.Integer(), nullable=False),
    sa.Column('weekly_plan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('available_days', sa.String(length=50), nullable=True),
    sa.Column('target_race_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('target_distance_miles', sa.Float(), nullable=True),
    sa.Column('target_pace_seconds', sa.Integer(), nullable=True),
    sa.Column('target_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('structure', sa.Text(), nullable=True),
    sa.Column('completed_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['completed_run_id'], ['run_sessions.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_segment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('segment_type', sa.String(length=20), nullable=False),
    sa.Column('target_pace_seconds', sa.Integer(), nullable=True),
    sa.Column('actual_pace_seconds', sa.Integer(), nullable=True),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_miles', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('run_sessions', sa.Column('planned_run_id', sa.Integer(), nullable=True))
    op.add_column('run_sessions', sa.Column('feel_rating', sa.Integer(), nullable=True))
    op.add_column('run_sessions', sa.Column('is_pr', sa.Boolean(), nullable=False))
    op.add_column('run_sessions', sa.Column('pr_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_sessions', 'pr_type')
    op.drop_column('run_sessions', 'is_pr')
    op.drop_column('run_sessions', 'feel_rating')
    op.drop_column('run_sessions', 'planned_run_id')
    op.drop_table('run_segment_logs')
    op.drop_table('planned_runs')
    op.drop_table('training_plans')
    # ### end Alembic commands ###
